### ISSUE TITLE
Undefined variable causes elasticpress sync error

### ISSUE THREAD

**Issue by mjvermeltfoort** [OnTheGoSystems/wpml-elasticpress#43]
The $forcePutMapping variable doesn't exist at this point which causes an error. 

https://github.com/OnTheGoSystems/wpml-elasticpress/blob/38aabe5ab91561dde24d0bd8c02884cb9125105e/src/Sync/Dashboard.php#L104

**Comment by decodekult** [comment]
Thanks for the report, @mjvermeltfoort 

I provided a pull request to fix this issue.
