### ISSUE TITLE
Fixes not included in the latest version

### ISSUE THREAD

**Issue by dingo-d** [OnTheGoSystems/wpml-elasticpress#52]
Hi!

I downloaded the wpml-elasticpress off your web when I log in (I have paid WPML), and the version there is 2.0.3, but I noticed that this fix https://github.com/OnTheGoSystems/wpml-elasticpress/pull/47 is not included.

Can you release version with all the fixes please, as it's causing issues down the line (https://github.com/10up/ElasticPress/issues/4011).

Thanks!

**Comment by decodekult** [comment]
Hi @dingo-d 

We just released WPML EñasticPress 2.0.4, which includes the solution for the issue that you referenced. It is available in your WPML account, over our custom update mechanism inside the WordPress admin interface, or in the latest release we publishe din this repository.

Once you confirm that the new version contains the fix that you referenced, I kindly ask you to get back here and close this issue.

Thanks in advance!

**Comment by dingo-d** [comment]
Ok will test it out! Thanks!

**Comment by dingo-d** [comment]
Works 👍🏼
