### ISSUE TITLE
No Posts on Archive page

### ISSUE THREAD

**Issue by burhandodhy** [OnTheGoSystems/wpml-elasticpress#7]
Hey, we found an issue where the plugin is not sending the correct language code on the archive page when the `use translation if available or fallback to default language` settings is set and there is no post in the secondary language .

On digging into the code, I found the plugin always sends the activated [language code ](https://github.com/OnTheGoSystems/wpml-elasticpress/blob/master/src/LanguageSearch.php#L87) without respecting the settings.

**Comment by strategio** [comment]
Thanks for reporting that @burhandodhy!

This plugin was initially developed for our own internal needs and we have a slow development pace on it. Therefore, I cannot give you any ETA for this to be fixed.

In turn, if you wish to contribute to this project, we would be very happy. Feel free to open a PR!

Thanks again!

Internal reference: **wpmlbridge-259**

**Comment by decodekult** [comment]
This has been fixed in https://github.com/OnTheGoSystems/wpml-elasticpress/pull/14 so closing here
