### ISSUE TITLE
This doesnt work

### ISSUE THREAD

**Issue by nickchomey** [OnTheGoSystems/wpml-elasticpress#8]
The plugin looks for an autoloader.php file that doesn't exist. Also, the main file should probably have the same `WPML/ElasticPress/` namespace as well.

**Comment by dgwatkins** [comment]
@nickchomey The autoloader files have to be created by running `composer install`.

You can download a release instead, which already contains the autoloader files:
https://github.com/OnTheGoSystems/wpml-elasticpress/releases

About the namespace, you are welcome to open a merge request with whatever you need.

**Comment by dgwatkins** [comment]
No problem @nickchomey, these things happen 😄 

I sent a pull request to add build instructions.
